modLoader="javafml"
loaderVersion="[33,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/StairwayToAether/issues"
[[mods]]
modId="stairway"
version="v15"
displayName="StairwayToAether"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stairway-to-aether"
logoFile="logo.png"
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''
This Mod brings you what should have always been in Minecraft in the first place. Stairs. And Slabs. And Walls.
And all the different Cobble and Brick variants for the currently available stone types.
So what you get is a whopping amount of over 300 new building blocks.
'''
[[dependencies.stairway]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2]"
    ordering="NONE"
    side="BOTH"