modLoader="javafml"
loaderVersion="[47,)" #mandatory
license="All rights reserved"
issueTrackerURL="https://github.com/Epidra/StairwayToAether/issues"
[[mods]]
modId="stairway"
version="18.0"
displayName="StairwayToAether"
displayURL="https://www.curseforge.com/minecraft/mc-mods/stairway-to-aether"
logoFile="logo.png"
credits="" #optional
authors="Epidra2077" #optional
description='''
This Mod brings you what should have always been in Minecraft in the first place. Stairs. And Slabs. And Walls.
And all the different Cobble and Brick variants for the currently available stone types.
So what you get is a whopping amount of over 300 new building blocks.
'''
[[dependencies.stairway]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.stairway]]
modId="acecraft"
mandatory=false
versionRange="[3.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.stairway]]
    modId="lucky77"
    mandatory=true
    versionRange="[3.0,)"
    ordering="NONE"
    side="BOTH"