package mod.stairway;

import mod.lucky77.block.BlockBlock;
import mod.stairway.block.*;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.CreativeModeTabEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.RegistryObject;

@Mod("stairway")
public class StairwayToAether {

    /** The Mod ID */
    public static final String MODID = "stairway";





    //----------------------------------------CONSTRUCTOR----------------------------------------//

    /** Default Constructor */
    public StairwayToAether() {
        MinecraftForge.EVENT_BUS.register(this);
        FMLJavaModLoadingContext.get().getModEventBus().addListener(this::setupCommon);
        FMLJavaModLoadingContext.get().getModEventBus().addListener(this::setupClient);
        FMLJavaModLoadingContext.get().getModEventBus().addListener(this::addCreative);
        StairKeeper.register();
    }





    //----------------------------------------SETUP----------------------------------------//

    private void setupCommon(final FMLCommonSetupEvent event){
        StairKeeper.setup(event);
    }

    private void setupClient(final FMLClientSetupEvent event) {
        StairKeeper.setup(event);
    }

    private void addCreative(CreativeModeTabEvent.BuildContents event) {
        if (event.getTab() == CreativeModeTabs.BUILDING_BLOCKS) {
            event.accept(StairKeeper.WALLS_STONE_STONES);
            event.accept(StairKeeper.PILAR_STONE_STONES);
            event.accept(StairKeeper.STAIR_STONE_SMOOTH);
            event.accept(StairKeeper.WALLS_STONE_SMOOTH);
            event.accept(StairKeeper.PILAR_STONE_SMOOTH);
            event.accept(StairKeeper.PILAR_STONE_COBBLE_BASIC);
            event.accept(StairKeeper.PILAR_STONE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_STONE_BRICKS_BASIC);
            event.accept(StairKeeper.PILAR_STONE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_STONE_BRICKS_CRACK);
            event.accept(StairKeeper.STAIR_STONE_BRICKS_CRACK);
            event.accept(StairKeeper.WALLS_STONE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_STONE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_GRANITE_STONES);
            event.accept(StairKeeper.WALLS_GRANITE_SMOOTH);
            event.accept(StairKeeper.PILAR_GRANITE_SMOOTH);
            event.accept(StairKeeper.BLOCK_GRANITE_COBBLE_BASIC);
            event.accept(StairKeeper.SLABS_GRANITE_COBBLE_BASIC);
            event.accept(StairKeeper.STAIR_GRANITE_COBBLE_BASIC);
            event.accept(StairKeeper.WALLS_GRANITE_COBBLE_BASIC);
            event.accept(StairKeeper.PILAR_GRANITE_COBBLE_BASIC);
            event.accept(StairKeeper.BLOCK_GRANITE_COBBLE_MOSSY);
            event.accept(StairKeeper.SLABS_GRANITE_COBBLE_MOSSY);
            event.accept(StairKeeper.STAIR_GRANITE_COBBLE_MOSSY);
            event.accept(StairKeeper.WALLS_GRANITE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_GRANITE_COBBLE_MOSSY);
            event.accept(StairKeeper.BLOCK_GRANITE_BRICKS_BASIC);
            event.accept(StairKeeper.SLABS_GRANITE_BRICKS_BASIC);
            event.accept(StairKeeper.STAIR_GRANITE_BRICKS_BASIC);
            event.accept(StairKeeper.WALLS_GRANITE_BRICKS_BASIC);
            event.accept(StairKeeper.PILAR_GRANITE_BRICKS_BASIC);
            event.accept(StairKeeper.BLOCK_GRANITE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_GRANITE_BRICKS_MOSSY);
            event.accept(StairKeeper.STAIR_GRANITE_BRICKS_MOSSY);
            event.accept(StairKeeper.WALLS_GRANITE_BRICKS_MOSSY);
            event.accept(StairKeeper.PILAR_GRANITE_BRICKS_MOSSY);
            event.accept(StairKeeper.BLOCK_GRANITE_BRICKS_CRACK);
            event.accept(StairKeeper.SLABS_GRANITE_BRICKS_CRACK);
            event.accept(StairKeeper.STAIR_GRANITE_BRICKS_CRACK);
            event.accept(StairKeeper.WALLS_GRANITE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_GRANITE_BRICKS_CRACK);
            event.accept(StairKeeper.BLOCK_GRANITE_CARVED);
            event.accept(StairKeeper.PILAR_DIORITE_STONES);
            event.accept(StairKeeper.WALLS_DIORITE_SMOOTH);
            event.accept(StairKeeper.PILAR_DIORITE_SMOOTH);
            event.accept(StairKeeper.BLOCK_DIORITE_COBBLE_BASIC);
            event.accept(StairKeeper.SLABS_DIORITE_COBBLE_BASIC);
            event.accept(StairKeeper.STAIR_DIORITE_COBBLE_BASIC);
            event.accept(StairKeeper.WALLS_DIORITE_COBBLE_BASIC);
            event.accept(StairKeeper.PILAR_DIORITE_COBBLE_BASIC);
            event.accept(StairKeeper.BLOCK_DIORITE_COBBLE_MOSSY);
            event.accept(StairKeeper.SLABS_DIORITE_COBBLE_MOSSY);
            event.accept(StairKeeper.STAIR_DIORITE_COBBLE_MOSSY);
            event.accept(StairKeeper.WALLS_DIORITE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_DIORITE_COBBLE_MOSSY);
            event.accept(StairKeeper.BLOCK_DIORITE_BRICKS_BASIC);
            event.accept(StairKeeper.SLABS_DIORITE_BRICKS_BASIC);
            event.accept(StairKeeper.STAIR_DIORITE_BRICKS_BASIC);
            event.accept(StairKeeper.WALLS_DIORITE_BRICKS_BASIC);
            event.accept(StairKeeper.PILAR_DIORITE_BRICKS_BASIC);
            event.accept(StairKeeper.BLOCK_DIORITE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_DIORITE_BRICKS_MOSSY);
            event.accept(StairKeeper.STAIR_DIORITE_BRICKS_MOSSY);
            event.accept(StairKeeper.WALLS_DIORITE_BRICKS_MOSSY);
            event.accept(StairKeeper.PILAR_DIORITE_BRICKS_MOSSY);
            event.accept(StairKeeper.BLOCK_DIORITE_BRICKS_CRACK);
            event.accept(StairKeeper.SLABS_DIORITE_BRICKS_CRACK);
            event.accept(StairKeeper.STAIR_DIORITE_BRICKS_CRACK);
            event.accept(StairKeeper.WALLS_DIORITE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_DIORITE_BRICKS_CRACK);
            event.accept(StairKeeper.BLOCK_DIORITE_CARVED);
            event.accept(StairKeeper.PILAR_ANDESITE_STONES);
            event.accept(StairKeeper.WALLS_ANDESITE_SMOOTH);
            event.accept(StairKeeper.PILAR_ANDESITE_SMOOTH);
            event.accept(StairKeeper.BLOCK_ANDESITE_COBBLE_BASIC);
            event.accept(StairKeeper.SLABS_ANDESITE_COBBLE_BASIC);
            event.accept(StairKeeper.STAIR_ANDESITE_COBBLE_BASIC);
            event.accept(StairKeeper.WALLS_ANDESITE_COBBLE_BASIC);
            event.accept(StairKeeper.PILAR_ANDESITE_COBBLE_BASIC);
            event.accept(StairKeeper.BLOCK_ANDESITE_COBBLE_MOSSY);
            event.accept(StairKeeper.SLABS_ANDESITE_COBBLE_MOSSY);
            event.accept(StairKeeper.STAIR_ANDESITE_COBBLE_MOSSY);
            event.accept(StairKeeper.WALLS_ANDESITE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_ANDESITE_COBBLE_MOSSY);
            event.accept(StairKeeper.BLOCK_ANDESITE_BRICKS_BASIC);
            event.accept(StairKeeper.SLABS_ANDESITE_BRICKS_BASIC);
            event.accept(StairKeeper.STAIR_ANDESITE_BRICKS_BASIC);
            event.accept(StairKeeper.WALLS_ANDESITE_BRICKS_BASIC);
            event.accept(StairKeeper.PILAR_ANDESITE_BRICKS_BASIC);
            event.accept(StairKeeper.BLOCK_ANDESITE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_ANDESITE_BRICKS_MOSSY);
            event.accept(StairKeeper.STAIR_ANDESITE_BRICKS_MOSSY);
            event.accept(StairKeeper.WALLS_ANDESITE_BRICKS_MOSSY);
            event.accept(StairKeeper.PILAR_ANDESITE_BRICKS_MOSSY);
            event.accept(StairKeeper.BLOCK_ANDESITE_BRICKS_CRACK);
            event.accept(StairKeeper.SLABS_ANDESITE_BRICKS_CRACK);
            event.accept(StairKeeper.STAIR_ANDESITE_BRICKS_CRACK);
            event.accept(StairKeeper.WALLS_ANDESITE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_ANDESITE_BRICKS_CRACK);
            event.accept(StairKeeper.BLOCK_ANDESITE_CARVED);
            event.accept(StairKeeper.PILAR_PRISMARINE_STONE);
            event.accept(StairKeeper.WALLS_PRISMARINE_BRICK);
            event.accept(StairKeeper.PILAR_PRISMARINE_BRICK);
            event.accept(StairKeeper.WALLS_PRISMARINE_DARK);
            event.accept(StairKeeper.PILAR_PRISMARINE_DARK);
            event.accept(StairKeeper.SLABS_ENDSTONE_STONES);
            event.accept(StairKeeper.STAIR_ENDSTONE_STONES);
            event.accept(StairKeeper.WALLS_ENDSTONE_STONES);
            event.accept(StairKeeper.PILAR_ENDSTONE_STONES);
            event.accept(StairKeeper.BLOCK_ENDSTONE_SMOOTH);
            event.accept(StairKeeper.SLABS_ENDSTONE_SMOOTH);
            event.accept(StairKeeper.STAIR_ENDSTONE_SMOOTH);
            event.accept(StairKeeper.WALLS_ENDSTONE_SMOOTH);
            event.accept(StairKeeper.PILAR_ENDSTONE_SMOOTH);
            event.accept(StairKeeper.BLOCK_ENDSTONE_COBBLE_BASIC);
            event.accept(StairKeeper.SLABS_ENDSTONE_COBBLE_BASIC);
            event.accept(StairKeeper.STAIR_ENDSTONE_COBBLE_BASIC);
            event.accept(StairKeeper.WALLS_ENDSTONE_COBBLE_BASIC);
            event.accept(StairKeeper.PILAR_ENDSTONE_COBBLE_BASIC);
            event.accept(StairKeeper.BLOCK_ENDSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.SLABS_ENDSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.STAIR_ENDSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.WALLS_ENDSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_ENDSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_ENDSTONE_BRICKS_BASIC);
            event.accept(StairKeeper.BLOCK_ENDSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_ENDSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.STAIR_ENDSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.WALLS_ENDSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.PILAR_ENDSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.BLOCK_ENDSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.SLABS_ENDSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.STAIR_ENDSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.WALLS_ENDSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_ENDSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.BLOCK_ENDSTONE_CARVED);
            event.accept(StairKeeper.PILAR_BLACKSTONE_SMOOTH);
            event.accept(StairKeeper.PILAR_BLACKSTONE_COBBLE_BASIC);
            event.accept(StairKeeper.BLOCK_BLACKSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.SLABS_BLACKSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.STAIR_BLACKSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.WALLS_BLACKSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_BLACKSTONE_COBBLE_MOSSY);
            event.accept(StairKeeper.PILAR_BLACKSTONE_BRICKS_BASIC);
            event.accept(StairKeeper.BLOCK_BLACKSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_BLACKSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.STAIR_BLACKSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.WALLS_BLACKSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.PILAR_BLACKSTONE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_BLACKSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.STAIR_BLACKSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.WALLS_BLACKSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_BLACKSTONE_BRICKS_CRACK);
            event.accept(StairKeeper.SLABS_DEEPSLATE_STONES);
            event.accept(StairKeeper.STAIR_DEEPSLATE_STONES);
            event.accept(StairKeeper.WALLS_DEEPSLATE_STONES);
            event.accept(StairKeeper.PILAR_DEEPSLATE_STONES);
            event.accept(StairKeeper.PILAR_DEEPSLATE_COBBLE_BASIC);
            event.accept(StairKeeper.BLOCK_DEEPSLATE_COBBLE_MOSS);
            event.accept(StairKeeper.SLABS_DEEPSLATE_COBBLE_MOSS);
            event.accept(StairKeeper.STAIR_DEEPSLATE_COBBLE_MOSS);
            event.accept(StairKeeper.WALLS_DEEPSLATE_COBBLE_MOSS);
            event.accept(StairKeeper.PILAR_DEEPSLATE_COBBLE_MOSS);
            event.accept(StairKeeper.PILAR_DEEPSLATE_SMOOTH);
            event.accept(StairKeeper.PILAR_DEEPSLATE_BRICKS_BASIC);
            event.accept(StairKeeper.BLOCK_DEEPSLATE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_DEEPSLATE_BRICKS_MOSSY);
            event.accept(StairKeeper.STAIR_DEEPSLATE_BRICKS_MOSSY);
            event.accept(StairKeeper.WALLS_DEEPSLATE_BRICKS_MOSSY);
            event.accept(StairKeeper.PILAR_DEEPSLATE_BRICKS_MOSSY);
            event.accept(StairKeeper.SLABS_DEEPSLATE_BRICKS_CRACK);
            event.accept(StairKeeper.STAIR_DEEPSLATE_BRICKS_CRACK);
            event.accept(StairKeeper.WALLS_DEEPSLATE_BRICKS_CRACK);
            event.accept(StairKeeper.PILAR_DEEPSLATE_BRICKS_CRACK);
            event.accept(StairKeeper.SLABS_CONCRETE_WHITE);
            event.accept(StairKeeper.STAIR_CONCRETE_WHITE);
            event.accept(StairKeeper.WALLS_CONCRETE_WHITE);
            event.accept(StairKeeper.PILAR_CONCRETE_WHITE);
            event.accept(StairKeeper.SLABS_CONCRETE_ORANGE);
            event.accept(StairKeeper.STAIR_CONCRETE_ORANGE);
            event.accept(StairKeeper.WALLS_CONCRETE_ORANGE);
            event.accept(StairKeeper.PILAR_CONCRETE_ORANGE);
            event.accept(StairKeeper.SLABS_CONCRETE_MAGENTA);
            event.accept(StairKeeper.STAIR_CONCRETE_MAGENTA);
            event.accept(StairKeeper.WALLS_CONCRETE_MAGENTA);
            event.accept(StairKeeper.PILAR_CONCRETE_MAGENTA);
            event.accept(StairKeeper.SLABS_CONCRETE_LIGHT_BLUE);
            event.accept(StairKeeper.STAIR_CONCRETE_LIGHT_BLUE);
            event.accept(StairKeeper.WALLS_CONCRETE_LIGHT_BLUE);
            event.accept(StairKeeper.PILAR_CONCRETE_LIGHT_BLUE);
            event.accept(StairKeeper.SLABS_CONCRETE_YELLOW);
            event.accept(StairKeeper.STAIR_CONCRETE_YELLOW);
            event.accept(StairKeeper.WALLS_CONCRETE_YELLOW);
            event.accept(StairKeeper.PILAR_CONCRETE_YELLOW);
            event.accept(StairKeeper.SLABS_CONCRETE_LIME);
            event.accept(StairKeeper.STAIR_CONCRETE_LIME);
            event.accept(StairKeeper.WALLS_CONCRETE_LIME);
            event.accept(StairKeeper.PILAR_CONCRETE_LIME);
            event.accept(StairKeeper.SLABS_CONCRETE_PINK);
            event.accept(StairKeeper.STAIR_CONCRETE_PINK);
            event.accept(StairKeeper.WALLS_CONCRETE_PINK);
            event.accept(StairKeeper.PILAR_CONCRETE_PINK);
            event.accept(StairKeeper.SLABS_CONCRETE_GRAY);
            event.accept(StairKeeper.STAIR_CONCRETE_GRAY);
            event.accept(StairKeeper.WALLS_CONCRETE_GRAY);
            event.accept(StairKeeper.PILAR_CONCRETE_GRAY);
            event.accept(StairKeeper.SLABS_CONCRETE_LIGHT_GRAY);
            event.accept(StairKeeper.STAIR_CONCRETE_LIGHT_GRAY);
            event.accept(StairKeeper.WALLS_CONCRETE_LIGHT_GRAY);
            event.accept(StairKeeper.PILAR_CONCRETE_LIGHT_GRAY);
            event.accept(StairKeeper.SLABS_CONCRETE_CYAN);
            event.accept(StairKeeper.STAIR_CONCRETE_CYAN);
            event.accept(StairKeeper.WALLS_CONCRETE_CYAN);
            event.accept(StairKeeper.PILAR_CONCRETE_CYAN);
            event.accept(StairKeeper.SLABS_CONCRETE_PURPLE);
            event.accept(StairKeeper.STAIR_CONCRETE_PURPLE);
            event.accept(StairKeeper.WALLS_CONCRETE_PURPLE);
            event.accept(StairKeeper.PILAR_CONCRETE_PURPLE);
            event.accept(StairKeeper.SLABS_CONCRETE_BLUE);
            event.accept(StairKeeper.STAIR_CONCRETE_BLUE);
            event.accept(StairKeeper.WALLS_CONCRETE_BLUE);
            event.accept(StairKeeper.PILAR_CONCRETE_BLUE);
            event.accept(StairKeeper.SLABS_CONCRETE_BROWN);
            event.accept(StairKeeper.STAIR_CONCRETE_BROWN);
            event.accept(StairKeeper.WALLS_CONCRETE_BROWN);
            event.accept(StairKeeper.PILAR_CONCRETE_BROWN);
            event.accept(StairKeeper.SLABS_CONCRETE_GREEN);
            event.accept(StairKeeper.STAIR_CONCRETE_GREEN);
            event.accept(StairKeeper.WALLS_CONCRETE_GREEN);
            event.accept(StairKeeper.PILAR_CONCRETE_GREEN);
            event.accept(StairKeeper.SLABS_CONCRETE_RED);
            event.accept(StairKeeper.STAIR_CONCRETE_RED);
            event.accept(StairKeeper.WALLS_CONCRETE_RED);
            event.accept(StairKeeper.PILAR_CONCRETE_RED);
            event.accept(StairKeeper.SLABS_CONCRETE_BLACK);
            event.accept(StairKeeper.STAIR_CONCRETE_BLACK);
            event.accept(StairKeeper.WALLS_CONCRETE_BLACK);
            event.accept(StairKeeper.PILAR_CONCRETE_BLACK);
            event.accept(StairKeeper.TIMBER_BASIC_WHITE);
            event.accept(StairKeeper.TIMBER_BASIC_ORANGE);
            event.accept(StairKeeper.TIMBER_BASIC_MAGENTA);
            event.accept(StairKeeper.TIMBER_BASIC_LIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_BASIC_YELLOW);
            event.accept(StairKeeper.TIMBER_BASIC_LIME);
            event.accept(StairKeeper.TIMBER_BASIC_PINK);
            event.accept(StairKeeper.TIMBER_BASIC_GRAY);
            event.accept(StairKeeper.TIMBER_BASIC_LIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_BASIC_CYAN);
            event.accept(StairKeeper.TIMBER_BASIC_PURPLE);
            event.accept(StairKeeper.TIMBER_BASIC_BLUE);
            event.accept(StairKeeper.TIMBER_BASIC_BROWN);
            event.accept(StairKeeper.TIMBER_BASIC_GREEN);
            event.accept(StairKeeper.TIMBER_BASIC_RED);
            event.accept(StairKeeper.TIMBER_BASIC_BLACK);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_WHITE);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_ORANGE);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_MAGENTA);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_LIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_YELLOW);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_LIME);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_PINK);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_GRAY);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_LIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_CYAN);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_PURPLE);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_BLUE);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_BROWN);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_GREEN);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_RED);
            event.accept(StairKeeper.TIMBER_HORIZONTAL_BLACK);
            event.accept(StairKeeper.TIMBER_VERTICAL_WHITE);
            event.accept(StairKeeper.TIMBER_VERTICAL_ORANGE);
            event.accept(StairKeeper.TIMBER_VERTICAL_MAGENTA);
            event.accept(StairKeeper.TIMBER_VERTICAL_LIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_VERTICAL_YELLOW);
            event.accept(StairKeeper.TIMBER_VERTICAL_LIME);
            event.accept(StairKeeper.TIMBER_VERTICAL_PINK);
            event.accept(StairKeeper.TIMBER_VERTICAL_GRAY);
            event.accept(StairKeeper.TIMBER_VERTICAL_LIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_VERTICAL_CYAN);
            event.accept(StairKeeper.TIMBER_VERTICAL_PURPLE);
            event.accept(StairKeeper.TIMBER_VERTICAL_BLUE);
            event.accept(StairKeeper.TIMBER_VERTICAL_BROWN);
            event.accept(StairKeeper.TIMBER_VERTICAL_GREEN);
            event.accept(StairKeeper.TIMBER_VERTICAL_RED);
            event.accept(StairKeeper.TIMBER_VERTICAL_BLACK);
            event.accept(StairKeeper.TIMBER_PLUS_WHITE);
            event.accept(StairKeeper.TIMBER_PLUS_ORANGE);
            event.accept(StairKeeper.TIMBER_PLUS_MAGENTA);
            event.accept(StairKeeper.TIMBER_PLUS_LIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_PLUS_YELLOW);
            event.accept(StairKeeper.TIMBER_PLUS_LIME);
            event.accept(StairKeeper.TIMBER_PLUS_PINK);
            event.accept(StairKeeper.TIMBER_PLUS_GRAY);
            event.accept(StairKeeper.TIMBER_PLUS_LIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_PLUS_CYAN);
            event.accept(StairKeeper.TIMBER_PLUS_PURPLE);
            event.accept(StairKeeper.TIMBER_PLUS_BLUE);
            event.accept(StairKeeper.TIMBER_PLUS_BROWN);
            event.accept(StairKeeper.TIMBER_PLUS_GREEN);
            event.accept(StairKeeper.TIMBER_PLUS_RED);
            event.accept(StairKeeper.TIMBER_PLUS_BLACK);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_WHITE);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_ORANGE);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_MAGENTA);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_LIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_YELLOW);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_LIME);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_PINK);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_GRAY);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_LIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_CYAN);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_PURPLE);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_BLUE);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_BROWN);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_GREEN);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_RED);
            event.accept(StairKeeper.TIMBER_DIAG_LEFT_BLACK);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_WHITE);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_ORANGE);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_MAGENTA);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_LIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_YELLOW);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_LIME);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_PINK);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_LIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_CYAN);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_PURPLE);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_BROWN);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_GREEN);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_RED);
            event.accept(StairKeeper.TIMBER_DIAG_RIGHT_BLACK);
            event.accept(StairKeeper.TIMBER_CROSS_WHITE);
            event.accept(StairKeeper.TIMBER_CROSS_ORANGE);
            event.accept(StairKeeper.TIMBER_CROSS_MAGENTA);
            event.accept(StairKeeper.TIMBER_CROSS_LIGHT_BLUE);
            event.accept(StairKeeper.TIMBER_CROSS_YELLOW);
            event.accept(StairKeeper.TIMBER_CROSS_LIME);
            event.accept(StairKeeper.TIMBER_CROSS_PINK);
            event.accept(StairKeeper.TIMBER_CROSS_GRAY);
            event.accept(StairKeeper.TIMBER_CROSS_LIGHT_GRAY);
            event.accept(StairKeeper.TIMBER_CROSS_CYAN);
            event.accept(StairKeeper.TIMBER_CROSS_PURPLE);
            event.accept(StairKeeper.TIMBER_CROSS_BLUE);
            event.accept(StairKeeper.TIMBER_CROSS_BROWN);
            event.accept(StairKeeper.TIMBER_CROSS_GREEN);
            event.accept(StairKeeper.TIMBER_CROSS_RED);
            event.accept(StairKeeper.TIMBER_CROSS_BLACK);
            event.accept(StairKeeper.BLOCK_SCAFFOLDING);
            event.accept(StairKeeper.BLOCK_CHAIN_COPPER);
            event.accept(StairKeeper.BLOCK_CHAIN_IRON);
            event.accept(StairKeeper.BLOCK_CHAIN_GOLD);
        }
        if (event.getTab() == CreativeModeTabs.REDSTONE_BLOCKS){
            event.accept(StairKeeper.STATUE_DOG_STONE          );
            event.accept(StairKeeper.STATUE_DOG_GRANITE        );
            event.accept(StairKeeper.STATUE_DOG_DIORITE        );
            event.accept(StairKeeper.STATUE_DOG_ANDESITE       );
            event.accept(StairKeeper.STATUE_DOG_ENDSTONE       );
            event.accept(StairKeeper.STATUE_DOG_BLACKSTONE     );
            event.accept(StairKeeper.STATUE_DOG_DEEPSLATE      );
            event.accept(StairKeeper.STATUE_CHICKEN_STONE      );
            event.accept(StairKeeper.STATUE_CHICKEN_GRANITE    );
            event.accept(StairKeeper.STATUE_CHICKEN_DIORITE    );
            event.accept(StairKeeper.STATUE_CHICKEN_ANDESITE   );
            event.accept(StairKeeper.STATUE_CHICKEN_ENDSTONE   );
            event.accept(StairKeeper.STATUE_CHICKEN_BLACKSTONE );
            event.accept(StairKeeper.STATUE_CHICKEN_DEEPSLATE  );
            event.accept(StairKeeper.BLOCK_EMITTER_WHITE       );
            event.accept(StairKeeper.BLOCK_EMITTER_ORANGE      );
            event.accept(StairKeeper.BLOCK_EMITTER_MAGENTA     );
            event.accept(StairKeeper.BLOCK_EMITTER_LIGHT_BLUE  );
            event.accept(StairKeeper.BLOCK_EMITTER_YELLOW      );
            event.accept(StairKeeper.BLOCK_EMITTER_LIME        );
            event.accept(StairKeeper.BLOCK_EMITTER_PINK        );
            event.accept(StairKeeper.BLOCK_EMITTER_GRAY        );
            event.accept(StairKeeper.BLOCK_EMITTER_LIGHT_GRAY  );
            event.accept(StairKeeper.BLOCK_EMITTER_CYAN        );
            event.accept(StairKeeper.BLOCK_EMITTER_PURPLE      );
            event.accept(StairKeeper.BLOCK_EMITTER_BLUE        );
            event.accept(StairKeeper.BLOCK_EMITTER_BROWN       );
            event.accept(StairKeeper.BLOCK_EMITTER_GREEN       );
            event.accept(StairKeeper.BLOCK_EMITTER_RED         );
            event.accept(StairKeeper.BLOCK_EMITTER_BLACK       );

        }
    }



}
